name: Build DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Install the Apple certificate and provisioning profile
    - name: Install Apple Certificate
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
        PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        
        # Import certificate and private key
        echo $CERTIFICATE_BASE64 | base64 --decode > certificate.pem
        echo $PRIVATE_KEY_BASE64 | base64 --decode > private_key.pem
        
        # Convert PEM to P12
        openssl pkcs12 -export \
          -in certificate.pem \
          -inkey private_key.pem \
          -out certificate.p12 \
          -passout pass:temp_password
        
        # Import into keychain
        security import certificate.p12 \
          -k build.keychain \
          -P temp_password \
          -T /usr/bin/codesign
        
        # Set keychain settings
        security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
        
        # Unlock keychain and allow codesign to access it
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
        
        # Verify certificate
        security find-identity -v -p codesigning build.keychain
    
    # Build the macOS app using xcodebuild
    - name: Build macOS App
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        CODE_SIGN_IDENTITY: ${{ vars.CODE_SIGN_IDENTITY || 'Developer ID Application' }}
        DEVELOPMENT_TEAM: ${{ vars.DEVELOPMENT_TEAM || 'NXWD68TXUQ' }}
      run: |
        xcodebuild -scheme "openterface" \
          -configuration Release \
          -archivePath "build/Openterface.xcarchive" \
          archive \
          CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
          CODE_SIGN_STYLE="Manual" \
          DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"
        
        xcodebuild -exportArchive \
          -archivePath "build/Openterface.xcarchive" \
          -exportPath "build/export" \
          -exportOptionsPlist exportOptions.plist

    # Notarize the app
    - name: Notarize App
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      run: |
        # Create temporary keychain
        xcrun notarytool store-credentials "notarytool-profile" \
          --apple-id "$APPLE_ID" \
          --password "$APPLE_APP_SPECIFIC_PASSWORD" \
          --team-id "NXWD68TXUQ"
        
        # Submit app for notarization
        xcrun notarytool submit "build/export/Openterface.app" \
          --keychain-profile "notarytool-profile" \
          --wait
        
        # Staple the notarization ticket
        xcrun stapler staple "build/export/Openterface.app"

    # Create DMG using create-dmg
    - name: Install create-dmg
      run: brew install create-dmg

    - name: Create DMG
      run: |
        create-dmg \
          --volname "Openterface" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "Openterface.app" 200 190 \
          --hide-extension "Openterface.app" \
          --app-drop-link 600 185 \
          "build/Openterface.dmg" \
          "build/export/Openterface.app"
        
    # Upload DMG as artifact
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: Openterface-dmg
        path: build/*.dmg
        
    # Create a release if tagged
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node- 

    - name: Debug Certificates
      run: |
        security find-identity -v -p codesigning
        security list-keychains
        security show-keychain-info build.keychain 